/// Aegis Authenticator (plain JSON export) → [OtpAccount] mapping.
///
/// Pure Dart: no Flutter, no plugins, no IO. The caller decodes the file and
/// hands over the root JSON object, so this parser can run inside
/// `Isolate.run` and be unit-tested on the host VM.
///
/// Expected shape (Aegis vault export, `version: 1`):
/// ```json
/// {"version":1,
///  "header":{"slots":null,"params":null},
///  "db":{"version":3,"entries":[
///     {"type":"totp","uuid":"…","name":"alice@example.com","issuer":"GitHub",
///      "note":"","favorite":false,"icon":null,
///      "info":{"secret":"…","algo":"SHA1","digits":6,"period":30}}]}}
/// ```
///
/// Tolerance decisions taken here (plan §2.1 "⚠" items) — each one prefers
/// dropping a single entry over inventing a token that would generate wrong
/// codes:
/// - **HOTP counter**: Aegis writes `info.counter`, but the field has also been
///   observed as `initialCounter` in third-party exporters that claim the Aegis
///   shape. Both names are tried, in that order. If neither is present the
///   entry is skipped with [SkipReason.invalidFields] — a HOTP counter is
///   moving state and guessing `0` would desynchronize the token forever.
/// - **Unsupported entry types**: anything other than `totp` / `hotp` / `steam`
///   (notably `yandex` and `motp`, whose "secret" is not an RFC 4648 Base32 OTP
///   secret at all) is skipped with [SkipReason.unsupportedType]. They are
///   deliberately NOT best-effort mapped to TOTP.
/// - **Steam is never inferred**: `type` is the only authority. Aegis writes
///   `"type": "steam"` for a Steam token, so an entry the file calls `totp`
///   stays an ordinary TOTP even when its issuer reads "Steam" — the format has
///   a first-class Steam type; guessing from issuer produces non-working codes.
/// - **Steam entries** (`type == "steam"`): `digits` is forced to 5 and
///   `algorithm` to SHA1 because Steam's codec is fixed and the file's values
///   are cosmetic; `period` is preserved when it is inside the 1..600 contract
///   of [OtpAccount], otherwise it falls back to 30 rather than dropping the
///   entry.
/// - **Algorithms**: a name a real export can carry but this app cannot compute
///   (`MD5`, which Aegis writes for MOTP entries, and the SHA-2 variants other
///   authenticators allow) is a capability gap, so it is skipped with
///   [SkipReason.unsupportedType] and an `algorithm=<NAME>` detail. A name no
///   authenticator writes is a broken file and stays
///   [SkipReason.invalidFields].
/// - **String ceilings**: `issuer` and `name` over [_maxStringBytes] UTF-8
///   bytes are rejected ([SkipReason.invalidFields]) instead of being written
///   into the vault, matching the ceiling the Google Authenticator path applies
///   to its protobuf strings.
/// - **Numeric fields** arriving as JSON strings or integer-valued doubles are
///   accepted; fractional numbers are rejected (never truncated), matching
///   `OtpAccount.fromJson`.
/// - `uuid`, `note`, `icon`, `icon_mime`, `icon_hash` and `favorite` are
///   ignored. A fresh id is generated by the [OtpAccount] constructor: the
///   Aegis uuid means nothing in this vault and reusing it could collide with a
///   real local id.
/// - **Groups → tags** (Phase 5 Patch 3, K6): `db.groups` is an array of
///   `{uuid, name}` and an entry references them by uuid in `entry.groups`.
///   Older exports carry a single `entry.group` holding the group NAME instead;
///   both are read, uuids first. A uuid with no matching group is dropped in
///   SILENCE — it produces no [SkippedEntry], because a stale group reference
///   says nothing about the token itself. NOTHING about groups can drop an
///   entry: every accessor here is total, and the ceilings (8 tags, 32 runes)
///   are applied by `OtpAccount.normalizeTags`, which never throws.
///
/// SECURITY: no secret is ever placed in a [SkippedEntry] label or detail, nor
/// in any exception message. Failures from `Base32.decode` (whose message
/// quotes the offending character) are caught and replaced with a fixed string.
library;

import 'dart:convert';

import '../../../core/otp/base32.dart';
import '../../../core/otp/otp_account.dart';
import '../../../core/otp/otp_algorithm.dart';
import '../domain/import_exceptions.dart';
import '../domain/import_models.dart';

/// Account name used when the source carries neither a name nor an issuer
/// (plan D4). User-facing text is Turkish by project convention.
const String _unnamedAccount = '(isimsiz)';

/// Longest free-form fragment copied from the file into a [SkippedEntry.detail].
const int _maxDetailFragment = 32;

/// Longest label fragment shown in the import preview. A file is untrusted
/// input: without this, an entry carrying a megabyte-long issuer would be
/// rendered verbatim.
const int _maxLabelPart = 64;

/// Ceiling for free-form strings copied into the vault, in UTF-8 bytes. Same
/// value as `ProtobufLimits.maxStringBytes` on the Google Authenticator path.
const int _maxStringBytes = 512;

/// Algorithm names a real export can carry but this app cannot compute. `MD5`
/// is what Aegis writes for MOTP entries; `SHA224`/`SHA384` are in the 2FAS
/// algorithm enum. They are a capability gap, not a malformed file.
const Set<String> _knownUnsupportedAlgorithms = {'MD5', 'SHA224', 'SHA384'};

class AegisParser implements ImportParser {
  const AegisParser();

  @override
  ImportSource get source => ImportSource.aegis;

  @override
  ParsedImport parse(Map<String, dynamic> json) {
    _rejectEncrypted(json);

    final db = json['db'];
    if (db is! Map) {
      throw const MalformedImportFileException('Aegis: "db" is not an object');
    }
    final entries = db['entries'];
    if (entries is! List) {
      throw const MalformedImportFileException(
          'Aegis: "db.entries" is not a list');
    }
    // A missing / wrongly typed `db.groups` yields an empty index, not an
    // error: the entries are still perfectly importable without their labels.
    final groups = _groupNamesByUuid(db['groups']);

    final accounts = <OtpAccount>[];
    final skipped = <SkippedEntry>[];

    for (final raw in entries) {
      if (raw is! Map) {
        skipped.add(const SkippedEntry(
          reason: SkipReason.invalidFields,
          detail: 'entry is not a JSON object',
        ));
        continue;
      }
      // The label is built before parsing so a failing entry is still
      // identifiable in the preview.
      final label = _label(_string(raw['issuer']), _string(raw['name']));
      try {
        accounts.add(_parseEntry(raw, groups));
      } on _Skip catch (skip) {
        skipped.add(SkippedEntry(
          label: label,
          reason: skip.reason,
          detail: skip.detail,
        ));
      } on FormatException {
        // Raised by OtpAccount.validate() / OtpAlgorithm.fromName for values we
        // did not screen ourselves. The message is NOT propagated: this parser
        // controls every string that reaches the UI.
        skipped.add(SkippedEntry(
          label: label,
          reason: SkipReason.invalidFields,
          detail: 'entry rejected by validation',
        ));
      } on ArgumentError {
        skipped.add(SkippedEntry(
          label: label,
          reason: SkipReason.invalidFields,
          detail: 'entry rejected by validation',
        ));
      }
    }

    return ParsedImport(
      source: ImportSource.aegis,
      accounts: accounts,
      skipped: skipped,
    );
  }

  /// Aegis marks a password-protected vault with a non-empty `header.slots`
  /// array; `db` is then a base64 string instead of an object. Either signal is
  /// enough — we do not implement Aegis' scrypt/AES-GCM slot format, the user
  /// must re-export unencrypted.
  void _rejectEncrypted(Map<String, dynamic> json) {
    final header = json['header'];
    if (header is Map) {
      final slots = header['slots'];
      if (slots is List && slots.isNotEmpty) {
        throw const EncryptedSourceException(ImportSource.aegis);
      }
    }
    if (json['db'] is String) {
      throw const EncryptedSourceException(ImportSource.aegis);
    }
  }

  /// `db.groups` → `uuid` → `name`. Rows missing either half, or carrying the
  /// wrong type, are skipped; the first row wins a duplicated uuid.
  Map<String, String> _groupNamesByUuid(Object? rawGroups) {
    if (rawGroups is! List) return const {};
    final index = <String, String>{};
    for (final raw in rawGroups) {
      if (raw is! Map) continue;
      final uuid = (_string(raw['uuid']) ?? '').trim();
      final name = (_string(raw['name']) ?? '').trim();
      if (uuid.isEmpty || name.isEmpty) continue;
      index.putIfAbsent(uuid, () => name);
    }
    return index;
  }

  /// Group NAMES for one entry, in file order. Never throws and never skips the
  /// entry — an unresolvable reference simply contributes no tag.
  ///
  /// The result is handed to [OtpAccount] unfiltered; its `normalizeTags` does
  /// the trimming, clipping and de-duplication, so an export with a 40-rune
  /// group name or twelve groups on one entry still imports.
  List<String> _tagsOf(Map<Object?, Object?> entry, Map<String, String> groups) {
    final tags = <String>[];
    final refs = entry['groups'];
    if (refs is List) {
      for (final ref in refs) {
        if (ref is! String) continue;
        final name = groups[ref.trim()];
        if (name != null) tags.add(name);
      }
    }
    // Legacy single-group field: it holds the NAME, not a uuid, so it is used
    // verbatim rather than looked up.
    final legacy = (_string(entry['group']) ?? '').trim();
    if (legacy.isNotEmpty) tags.add(legacy);
    return tags;
  }

  OtpAccount _parseEntry(
      Map<Object?, Object?> entry, Map<String, String> groups) {
    final typeName = (_string(entry['type']) ?? '').trim();
    if (typeName.isEmpty) {
      throw const _Skip(SkipReason.invalidFields, 'entry has no "type"');
    }
    final declared = _typeFromName(typeName);
    if (declared == null) {
      throw _Skip(
          SkipReason.unsupportedType, 'type=${_fragment(typeName)}');
    }

    final info = entry['info'];
    if (info is! Map) {
      throw const _Skip(SkipReason.invalidFields, 'entry has no "info" object');
    }

    final issuerRaw = (_string(entry['issuer']) ?? '').trim();
    final nameRaw = (_string(entry['name']) ?? '').trim();
    _requireStringCap(issuerRaw, 'issuer');
    _requireStringCap(nameRaw, 'name');
    final issuer = issuerRaw.isEmpty ? null : issuerRaw;
    // Plan D4: empty name falls back to the issuer, then to a placeholder, so
    // the vault never shows a blank row.
    final accountName =
        nameRaw.isNotEmpty ? nameRaw : (issuer ?? _unnamedAccount);

    final secret = (_string(info['secret']) ?? '').trim();
    if (secret.isEmpty) {
      throw const _Skip(SkipReason.invalidSecret, 'secret missing or empty');
    }
    _requireDecodableSecret(secret);

    // `type` is the authority; there is no issuer heuristic (library doc).
    final type = declared;

    final int digits;
    final int period;
    final OtpAlgorithm algorithm;
    if (type == OtpType.steam) {
      digits = 5;
      algorithm = OtpAlgorithm.sha1;
      final rawPeriod = _integer(info['period'], 'period');
      period = (rawPeriod != null && rawPeriod >= 1 && rawPeriod <= 600)
          ? rawPeriod
          : 30;
    } else {
      digits = _integer(info['digits'], 'digits') ?? 6;
      period = _integer(info['period'], 'period') ?? 30;
      algorithm = _algorithm(_string(info['algo']));
    }

    final int counter;
    if (type == OtpType.hotp) {
      final parsed = _counter(info);
      if (parsed == null) {
        throw const _Skip(SkipReason.invalidFields,
            'HOTP entry has no counter (tried "counter", "initialCounter")');
      }
      counter = parsed;
    } else {
      counter = 0;
    }

    try {
      return OtpAccount(
        secret: secret,
        type: type,
        issuer: issuer,
        accountName: accountName,
        algorithm: algorithm,
        digits: digits,
        period: period,
        counter: counter,
        tags: _tagsOf(entry, groups),
      );
    } on FormatException {
      // Out-of-contract numbers (digits 9, period 0, ...). The detail lists the
      // offending values only — never the secret.
      throw _Skip(SkipReason.invalidFields,
          'digits=$digits period=$period counter=$counter');
    }
  }

  /// HOTP counter under either of the field names seen in the wild.
  int? _counter(Map<Object?, Object?> info) {
    for (final key in const ['counter', 'initialCounter']) {
      if (info.containsKey(key)) {
        final value = _integer(info[key], key);
        if (value != null) return value;
      }
    }
    return null;
  }

  /// Separates "an algorithm we know of but cannot compute" from "an algorithm
  /// nobody writes". [OtpAlgorithm.fromName] cannot make that distinction — it
  /// raises one [FormatException] for both — so the name is classified here,
  /// leaving `fromName` and its `otpauth://` callers untouched.
  OtpAlgorithm _algorithm(String? raw) {
    final name = (raw ?? '').trim();
    if (name.isEmpty) return OtpAlgorithm.sha1;
    final canonical = name.toUpperCase().replaceAll('-', '');
    try {
      return OtpAlgorithm.fromName(canonical);
    } on FormatException {
      if (_knownUnsupportedAlgorithms.contains(canonical)) {
        throw _Skip(SkipReason.unsupportedType, 'algorithm=$canonical');
      }
      throw _Skip(SkipReason.invalidFields,
          'unsupported algorithm ${_fragment(name)}');
    }
  }

  /// Fails fast on a secret the OTP engine could not use, without letting
  /// `Base32.decode`'s message (which quotes the bad character) escape.
  void _requireDecodableSecret(String secret) {
    try {
      if (Base32.decode(secret).isEmpty) {
        throw const _Skip(
            SkipReason.invalidSecret, 'secret decodes to zero bytes');
      }
    } on FormatException {
      throw const _Skip(SkipReason.invalidSecret, 'secret is not valid Base32');
    }
  }
}

OtpType? _typeFromName(String raw) => switch (raw.toLowerCase()) {
      'totp' => OtpType.totp,
      'hotp' => OtpType.hotp,
      'steam' => OtpType.steam,
      _ => null,
    };

/// String-or-nothing accessor: a wrongly typed JSON value becomes `null`
/// instead of a `TypeError`, so label building can never throw.
String? _string(Object? value) => value is String ? value : null;

/// Tolerant integer accessor. `null` when absent; [_Skip] when present but not
/// an integer. Integer-valued doubles and numeric strings are accepted;
/// fractional values are rejected rather than truncated.
int? _integer(Object? value, String field) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is double && value == value.truncateToDouble()) return value.toInt();
  if (value is String) {
    final parsed = int.tryParse(value.trim());
    if (parsed != null) return parsed;
  }
  throw _Skip(SkipReason.invalidFields, '"$field" is not an integer');
}

/// Rejects a free-form string too long to belong in the vault. Byte length,
/// not code units: the ceiling has to mean the same thing for a Turkish issuer
/// as for an ASCII one.
void _requireStringCap(String value, String field) {
  if (utf8.encode(value).length > _maxStringBytes) {
    throw _Skip(
        SkipReason.invalidFields, '"$field" is over $_maxStringBytes bytes');
  }
}

String? _label(String? issuer, String? name) {
  final i = _labelPart(issuer);
  final n = _labelPart(name);
  if (i.isNotEmpty && n.isNotEmpty) return '$i ($n)';
  if (i.isNotEmpty) return i;
  if (n.isNotEmpty) return n;
  return null;
}

/// Trimmed and clamped: a [SkippedEntry.label] is rendered verbatim, so an
/// oversized string from the file must not reach the preview.
String _labelPart(String? value) {
  final trimmed = (value ?? '').trim();
  return trimmed.length <= _maxLabelPart
      ? trimmed
      : '${trimmed.substring(0, _maxLabelPart)}…';
}

String _fragment(String value) => value.length <= _maxDetailFragment
    ? '"$value"'
    : '"${value.substring(0, _maxDetailFragment)}…"';

/// Internal control-flow signal: "drop this entry, keep the file".
class _Skip implements Exception {
  final SkipReason reason;
  final String detail;
  const _Skip(this.reason, this.detail);
}
