/// 2FAS Authenticator (plain JSON export, `schemaVersion` 4) → [OtpAccount].
///
/// Pure Dart: no Flutter, no plugins, no IO. The caller decodes the file and
/// hands over the root JSON object, so this parser can run inside
/// `Isolate.run` and be unit-tested on the host VM.
///
/// Expected shape:
/// ```json
/// {"services":[
///    {"name":"GitHub","secret":"…","updatedAt":1699999999999,
///     "otp":{"label":"GitHub","account":"alice@example.com","issuer":"GitHub",
///            "digits":6,"period":30,"algorithm":"SHA1","tokenType":"TOTP",
///            "source":"Link","link":"otpauth://…"},
///     "order":{"position":0},"icon":{…},"groupId":null}],
///  "groups":[],"updatedAt":1699999999999,"schemaVersion":4,
///  "appVersionCode":50000,"appOrigin":"android"}
/// ```
/// Note the secret lives on the **service root**, not inside `otp`.
///
/// Tolerance decisions taken here (plan §2.2 "⚠" items) — each one prefers
/// dropping a single entry over inventing a token that would generate wrong
/// codes:
/// - **Missing `otp.tokenType`**: older 2FAS schemas omit it entirely. Absent
///   or empty is read as `TOTP`, which is what 2FAS itself assumes and what the
///   `otpauth://` default is. An unknown non-empty value is NOT guessed — the
///   entry is skipped with [SkipReason.unsupportedType].
/// - **HOTP counter**: 2FAS has shipped both `otp.counter` and
///   `otp.initialCounter`. Both names are tried, in that order. If neither is
///   present the entry is skipped with [SkipReason.invalidFields] rather than
///   defaulting to `0`: a HOTP counter is moving state and a wrong start value
///   desynchronizes the token forever.
/// - **Missing `otp` object**: treated as an empty object, so a service that
///   only carries `name` + `secret` still imports as a default TOTP token.
/// - **Missing root `secret`**: falls back to the `secret` query parameter of
///   `otp.link` when that link is an `otpauth://` URI. Only the secret is taken
///   from the link; every other field keeps its structured value, because the
///   link is a stale "source" copy in 2FAS and can disagree with the edited
///   fields.
/// - **Steam entries** (plan §2.3): `digits` is forced to 5 and `algorithm` to
///   SHA1 because Steam's codec is fixed; `period` is preserved when it is
///   inside the 1..600 contract of [OtpAccount], otherwise it falls back to 30.
/// - `order`, `icon`, `badge`, `groupId`, `groups` and `updatedAt` are ignored.
///   A fresh id is generated by the [OtpAccount] constructor.
///
/// SECURITY: no secret is ever placed in a [SkippedEntry] label or detail, nor
/// in any exception message. Failures from `Base32.decode` (whose message
/// quotes the offending character) are caught and replaced with a fixed string.
library;

import '../../../core/otp/base32.dart';
import '../../../core/otp/otp_account.dart';
import '../../../core/otp/otp_algorithm.dart';
import '../domain/import_exceptions.dart';
import '../domain/import_models.dart';

/// Account name used when the source carries no usable name (plan D4).
/// User-facing text is Turkish by project convention.
const String _unnamedAccount = '(isimsiz)';

/// Longest free-form fragment copied from the file into a [SkippedEntry.detail].
const int _maxDetailFragment = 32;

class TwoFasParser implements ImportParser {
  const TwoFasParser();

  @override
  ImportSource get source => ImportSource.twofas;

  @override
  ParsedImport parse(Map<String, dynamic> json) {
    _rejectEncrypted(json);

    final services = json['services'];
    if (services is! List) {
      throw const MalformedImportFileException(
          '2FAS: "services" is not a list');
    }

    final accounts = <OtpAccount>[];
    final skipped = <SkippedEntry>[];

    for (final raw in services) {
      if (raw is! Map) {
        skipped.add(const SkippedEntry(
          reason: SkipReason.invalidFields,
          detail: 'service is not a JSON object',
        ));
        continue;
      }
      final otp = raw['otp'];
      final otpMap = otp is Map ? otp : const <Object?, Object?>{};
      // The label is built before parsing so a failing entry is still
      // identifiable in the preview.
      final label = _label(
        _firstNonEmpty([otpMap['issuer'], raw['name']]),
        _firstNonEmpty([otpMap['account'], otpMap['label'], raw['name']]),
      );
      try {
        accounts.add(_parseService(raw, otpMap));
      } on _Skip catch (skip) {
        skipped.add(SkippedEntry(
          label: label,
          reason: skip.reason,
          detail: skip.detail,
        ));
      } on FormatException {
        // Raised by OtpAccount.validate() / OtpAlgorithm.fromName for values we
        // did not screen ourselves. The message is NOT propagated: this parser
        // controls every string that reaches the UI.
        skipped.add(SkippedEntry(
          label: label,
          reason: SkipReason.invalidFields,
          detail: 'entry rejected by validation',
        ));
      } on ArgumentError {
        skipped.add(SkippedEntry(
          label: label,
          reason: SkipReason.invalidFields,
          detail: 'entry rejected by validation',
        ));
      }
    }

    return ParsedImport(
      source: ImportSource.twofas,
      accounts: accounts,
      skipped: skipped,
    );
  }

  /// A 2FAS export protected by the app's own password keeps `services` empty
  /// and moves everything into `servicesEncrypted` ("cipher:salt:iv" base64).
  /// We do not implement 2FAS' PBKDF2/AES-GCM scheme — the user must export
  /// without a password. An empty/absent value is NOT encrypted.
  void _rejectEncrypted(Map<String, dynamic> json) {
    final encrypted = json['servicesEncrypted'];
    if (encrypted is String && encrypted.trim().isNotEmpty) {
      throw const EncryptedSourceException(ImportSource.twofas);
    }
    if (encrypted is List && encrypted.isNotEmpty) {
      throw const EncryptedSourceException(ImportSource.twofas);
    }
  }

  OtpAccount _parseService(
      Map<Object?, Object?> service, Map<Object?, Object?> otp) {
    final declared = _tokenType(otp['tokenType']);

    final serviceName = (_string(service['name']) ?? '').trim();
    final otpIssuer = (_string(otp['issuer']) ?? '').trim();
    final issuerRaw = otpIssuer.isNotEmpty ? otpIssuer : serviceName;
    final issuer = issuerRaw.isEmpty ? null : issuerRaw;
    // Plan D4: account → label → service name → placeholder.
    final accountName =
        _firstNonEmpty([otp['account'], otp['label'], service['name']]) ??
            _unnamedAccount;

    var secret = (_string(service['secret']) ?? '').trim();
    if (secret.isEmpty) {
      secret = _secretFromLink(_string(otp['link'])) ?? '';
    }
    if (secret.isEmpty) {
      throw const _Skip(SkipReason.invalidSecret, 'secret missing or empty');
    }
    _requireDecodableSecret(secret);

    // Plan D5: a TOTP entry whose issuer is "Steam" is really a Steam token.
    final isSteam = declared == OtpType.steam ||
        (declared == OtpType.totp && issuerRaw.toLowerCase() == 'steam');
    final type = isSteam ? OtpType.steam : declared;

    final int digits;
    final int period;
    final OtpAlgorithm algorithm;
    if (isSteam) {
      digits = 5;
      algorithm = OtpAlgorithm.sha1;
      final rawPeriod = _integer(otp['period'], 'period');
      period = (rawPeriod != null && rawPeriod >= 1 && rawPeriod <= 600)
          ? rawPeriod
          : 30;
    } else {
      digits = _integer(otp['digits'], 'digits') ?? 6;
      period = _integer(otp['period'], 'period') ?? 30;
      algorithm = _algorithm(_string(otp['algorithm']));
    }

    final int counter;
    if (type == OtpType.hotp) {
      final parsed = _counter(otp);
      if (parsed == null) {
        throw const _Skip(SkipReason.invalidFields,
            'HOTP entry has no counter (tried "counter", "initialCounter")');
      }
      counter = parsed;
    } else {
      counter = 0;
    }

    try {
      return OtpAccount(
        secret: secret,
        type: type,
        issuer: issuer,
        accountName: accountName,
        algorithm: algorithm,
        digits: digits,
        period: period,
        counter: counter,
      );
    } on FormatException {
      // Out-of-contract numbers (digits 9, period 0, ...). The detail lists the
      // offending values only — never the secret.
      throw _Skip(SkipReason.invalidFields,
          'digits=$digits period=$period counter=$counter');
    }
  }

  OtpType _tokenType(Object? raw) {
    final name = (_string(raw) ?? '').trim();
    // Absent/empty tokenType means TOTP (see class doc).
    if (name.isEmpty) return OtpType.totp;
    return switch (name.toUpperCase()) {
      'TOTP' => OtpType.totp,
      'HOTP' => OtpType.hotp,
      'STEAM' => OtpType.steam,
      _ => throw _Skip(
          SkipReason.unsupportedType, 'tokenType=${_fragment(name)}'),
    };
  }

  /// HOTP counter under either of the field names 2FAS has shipped.
  int? _counter(Map<Object?, Object?> otp) {
    for (final key in const ['counter', 'initialCounter']) {
      if (otp.containsKey(key)) {
        final value = _integer(otp[key], key);
        if (value != null) return value;
      }
    }
    return null;
  }

  OtpAlgorithm _algorithm(String? raw) {
    try {
      return OtpAlgorithm.fromName(raw);
    } on FormatException {
      throw _Skip(SkipReason.invalidFields,
          'unsupported algorithm ${_fragment(raw ?? '')}');
    }
  }

  /// Extracts only the `secret` query parameter of an `otpauth://` link.
  /// Returns null for anything else, including malformed percent-encoding.
  String? _secretFromLink(String? link) {
    if (link == null || link.isEmpty) return null;
    final uri = Uri.tryParse(link.trim());
    if (uri == null || uri.scheme.toLowerCase() != 'otpauth') return null;
    try {
      final secret = uri.queryParameters['secret'];
      return (secret == null || secret.isEmpty) ? null : secret;
    } on FormatException {
      return null;
    }
  }

  /// Fails fast on a secret the OTP engine could not use, without letting
  /// `Base32.decode`'s message (which quotes the bad character) escape.
  void _requireDecodableSecret(String secret) {
    try {
      if (Base32.decode(secret).isEmpty) {
        throw const _Skip(
            SkipReason.invalidSecret, 'secret decodes to zero bytes');
      }
    } on FormatException {
      throw const _Skip(SkipReason.invalidSecret, 'secret is not valid Base32');
    }
  }
}

/// String-or-nothing accessor: a wrongly typed JSON value becomes `null`
/// instead of a `TypeError`, so label building can never throw.
String? _string(Object? value) => value is String ? value : null;

/// First value that is a non-blank String, trimmed; null when there is none.
String? _firstNonEmpty(List<Object?> candidates) {
  for (final candidate in candidates) {
    final value = (_string(candidate) ?? '').trim();
    if (value.isNotEmpty) return value;
  }
  return null;
}

/// Tolerant integer accessor. `null` when absent; [_Skip] when present but not
/// an integer. Integer-valued doubles and numeric strings are accepted;
/// fractional values are rejected rather than truncated.
int? _integer(Object? value, String field) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is double && value == value.truncateToDouble()) return value.toInt();
  if (value is String) {
    final parsed = int.tryParse(value.trim());
    if (parsed != null) return parsed;
  }
  throw _Skip(SkipReason.invalidFields, '"$field" is not an integer');
}

String? _label(String? issuer, String? name) {
  final i = (issuer ?? '').trim();
  final n = (name ?? '').trim();
  if (i.isNotEmpty && n.isNotEmpty) return '$i ($n)';
  if (i.isNotEmpty) return i;
  if (n.isNotEmpty) return n;
  return null;
}

String _fragment(String value) => value.length <= _maxDetailFragment
    ? '"$value"'
    : '"${value.substring(0, _maxDetailFragment)}…"';

/// Internal control-flow signal: "drop this entry, keep the file".
class _Skip implements Exception {
  final SkipReason reason;
  final String detail;
  const _Skip(this.reason, this.detail);
}
