/// 2FAS Authenticator (plain JSON export, `schemaVersion` 4) → [OtpAccount].
///
/// Pure Dart: no Flutter, no plugins, no IO. The caller decodes the file and
/// hands over the root JSON object, so this parser can run inside
/// `Isolate.run` and be unit-tested on the host VM.
///
/// Expected shape:
/// ```json
/// {"services":[
///    {"name":"GitHub","secret":"…","updatedAt":1699999999999,
///     "otp":{"label":"GitHub","account":"alice@example.com","issuer":"GitHub",
///            "digits":6,"period":30,"algorithm":"SHA1","tokenType":"TOTP",
///            "source":"Link","link":"otpauth://…"},
///     "order":{"position":0},"icon":{…},"groupId":null}],
///  "groups":[],"updatedAt":1699999999999,"schemaVersion":4,
///  "appVersionCode":50000,"appOrigin":"android"}
/// ```
/// Note the secret lives on the **service root**, not inside `otp`.
///
/// Tolerance decisions taken here (plan §2.2 "⚠" items) — each one prefers
/// dropping a single entry over inventing a token that would generate wrong
/// codes:
/// - **Missing `otp.tokenType`**: older 2FAS schemas omit it entirely. Absent
///   or empty is read as `TOTP`, which is what 2FAS itself assumes and what the
///   `otpauth://` default is. An unknown non-empty value is NOT guessed — the
///   entry is skipped with [SkipReason.unsupportedType].
/// - **HOTP counter**: `otp.counter` is the only name the official exporter
///   writes (`BackupService.Otp`). `otp.initialCounter` is also tried as a
///   defensive fallback for third-party writers; it is not observed in official
///   exports. If neither is present the entry is skipped with
///   [SkipReason.invalidFields] rather than defaulting to `0`: a HOTP counter is
///   moving state and a wrong start value desynchronizes the token forever.
/// - **Missing `otp` object**: treated as an empty object, so a service that
///   only carries `name` + `secret` still imports as a default TOTP token.
/// - **Missing root `secret`**: falls back to the `secret` query parameter of
///   `otp.link` when that link is an `otpauth://` URI. Only the secret is taken
///   from the link; every other field keeps its structured value, because the
///   link is a stale "source" copy in 2FAS and can disagree with the edited
///   fields. A link whose `secret` is a bracketed placeholder (`[hidden]` and
///   friends) is a redacted copy, not a secret, and gets a 2FAS-specific skip
///   detail telling the user to re-export.
/// - **Steam is never inferred**: `otp.tokenType` is the only authority. 2FAS
///   writes `"tokenType": "STEAM"` for a Steam token, so a service the file
///   calls `TOTP` stays an ordinary TOTP even when its issuer reads "Steam" —
///   the format has a first-class Steam type; guessing from issuer produces
///   non-working codes.
/// - **Steam entries** (`tokenType == "STEAM"`): `digits` is forced to 5 and
///   `algorithm` to SHA1 because Steam's codec is fixed; `period` is preserved
///   when it is inside the 1..600 contract of [OtpAccount], otherwise it falls
///   back to 30.
/// - **Algorithms**: `SHA224` and `SHA384` are in the 2FAS algorithm enum but
///   this app cannot compute them, so they are a capability gap:
///   [SkipReason.unsupportedType] with an `algorithm=<NAME>` detail. A name
///   outside that enum is a broken file and stays
///   [SkipReason.invalidFields].
/// - **String ceilings**: `name`, `otp.issuer` and `otp.account` over
///   [_maxStringBytes] UTF-8 bytes are rejected ([SkipReason.invalidFields])
///   instead of being written into the vault, matching the ceiling the Google
///   Authenticator path applies to its protobuf strings.
/// - `order`, `icon`, `badge` and `updatedAt` are ignored. A fresh id is
///   generated by the [OtpAccount] constructor.
/// - **Groups → tags** (Phase 5 Patch 3, K6): the root `groups` array holds
///   `{id, name}` rows and a service points at one of them with `groupId`, so a
///   2FAS service yields AT MOST ONE tag. `groupId: null` (the default in every
///   export) and an id with no matching row both yield NO tag, in SILENCE — a
///   stale group reference says nothing about the token itself and produces no
///   [SkippedEntry]. NOTHING about groups can drop a service: every accessor
///   here is total and the ceilings are applied by `OtpAccount.normalizeTags`,
///   which never throws.
///
/// SECURITY: no secret is ever placed in a [SkippedEntry] label or detail, nor
/// in any exception message. Failures from `Base32.decode` (whose message
/// quotes the offending character) are caught and replaced with a fixed string.
library;

import 'dart:convert';

import '../../../core/otp/base32.dart';
import '../../../core/otp/otp_account.dart';
import '../../../core/otp/otp_algorithm.dart';
import '../domain/import_exceptions.dart';
import '../domain/import_models.dart';

/// Account name used when the source carries no usable name (plan D4).
/// User-facing text is Turkish by project convention.
const String _unnamedAccount = '(isimsiz)';

/// Longest free-form fragment copied from the file into a [SkippedEntry.detail].
const int _maxDetailFragment = 32;

/// Longest label fragment shown in the import preview. A file is untrusted
/// input: without this, a service carrying a megabyte-long name would be
/// rendered verbatim.
const int _maxLabelPart = 64;

/// Ceiling for free-form strings copied into the vault, in UTF-8 bytes. Same
/// value as `ProtobufLimits.maxStringBytes` on the Google Authenticator path.
const int _maxStringBytes = 512;

/// Algorithm names the 2FAS enum allows but this app cannot compute. A
/// capability gap, not a malformed file.
const Set<String> _knownUnsupportedAlgorithms = {'SHA224', 'SHA384', 'MD5'};

class TwoFasParser implements ImportParser {
  const TwoFasParser();

  @override
  ImportSource get source => ImportSource.twofas;

  @override
  ParsedImport parse(Map<String, dynamic> json) {
    _rejectEncrypted(json);

    final services = json['services'];
    if (services is! List) {
      throw const MalformedImportFileException(
        '2FAS: "services" is not a list',
      );
    }

    // A missing / wrongly typed root `groups` yields an empty index, not an
    // error: the services are still perfectly importable without their labels.
    final groups = _groupNamesById(json['groups']);

    final accounts = <OtpAccount>[];
    final skipped = <SkippedEntry>[];

    for (final raw in services) {
      if (raw is! Map) {
        skipped.add(
          const SkippedEntry(
            reason: SkipReason.invalidFields,
            detail: 'service is not a JSON object',
          ),
        );
        continue;
      }
      final otp = raw['otp'];
      final otpMap = otp is Map ? otp : const <Object?, Object?>{};
      // The label is built before parsing so a failing entry is still
      // identifiable in the preview.
      final label = _label(
        _firstNonEmpty([otpMap['issuer'], raw['name']]),
        _firstNonEmpty([otpMap['account'], otpMap['label'], raw['name']]),
      );
      try {
        accounts.add(_parseService(raw, otpMap, groups));
      } on _Skip catch (skip) {
        skipped.add(
          SkippedEntry(label: label, reason: skip.reason, detail: skip.detail),
        );
      } on FormatException {
        // Raised by OtpAccount.validate() / OtpAlgorithm.fromName for values we
        // did not screen ourselves. The message is NOT propagated: this parser
        // controls every string that reaches the UI.
        skipped.add(
          SkippedEntry(
            label: label,
            reason: SkipReason.invalidFields,
            detail: 'entry rejected by validation',
          ),
        );
      } on ArgumentError {
        skipped.add(
          SkippedEntry(
            label: label,
            reason: SkipReason.invalidFields,
            detail: 'entry rejected by validation',
          ),
        );
      }
    }

    return ParsedImport(
      source: ImportSource.twofas,
      accounts: accounts,
      skipped: skipped,
    );
  }

  /// A 2FAS export protected by the app's own password keeps `services` empty
  /// and moves everything into `servicesEncrypted` ("cipher:salt:iv" base64),
  /// alongside a `reference` blob in the same shape — a known plaintext
  /// encrypted under the same key, which 2FAS uses to verify the password.
  ///
  /// `reference` is the official predicate: `BackupContent.isEncrypted` is
  /// exactly `reference.isNullOrBlank().not()`. `servicesEncrypted` is checked
  /// too, so a writer that ships the payload without the reference is still
  /// recognized. We do not implement 2FAS' PBKDF2/AES-GCM scheme — the user
  /// must export without a password. An empty/absent value is NOT encrypted.
  void _rejectEncrypted(Map<String, dynamic> json) {
    final reference = json['reference'];
    if (reference is String && reference.trim().isNotEmpty) {
      throw const EncryptedSourceException(ImportSource.twofas);
    }

    final encrypted = json['servicesEncrypted'];
    if (encrypted is String && encrypted.trim().isNotEmpty) {
      throw const EncryptedSourceException(ImportSource.twofas);
    }
    if (encrypted is List && encrypted.isNotEmpty) {
      throw const EncryptedSourceException(ImportSource.twofas);
    }
  }

  /// Root `groups` → `id` → `name`. Rows missing either half are skipped; the
  /// first row wins a duplicated id.
  ///
  /// Ids are keyed by their STRING form: 2FAS writes uuids, but exports in the
  /// wild (and hand-edited files) also carry plain integer ids, and a `7` that
  /// failed to match `"7"` would silently cost the token its group. The name
  /// still has to be a real String — a number is not a label.
  Map<String, String> _groupNamesById(Object? rawGroups) {
    if (rawGroups is! List) return const {};
    final index = <String, String>{};
    for (final raw in rawGroups) {
      if (raw is! Map) continue;
      final id = _groupId(raw['id']);
      final name = (_string(raw['name']) ?? '').trim();
      if (id.isEmpty || name.isEmpty) continue;
      index.putIfAbsent(id, () => name);
    }
    return index;
  }

  /// A group id in its comparable form: Strings verbatim, numbers via
  /// [Object.toString], anything else (map, list, bool, null) → empty, i.e. no
  /// group. Trimmed at both ends so `" 7 "` and `7` land on the same key.
  String _groupId(Object? value) {
    if (value is String) return value.trim();
    if (value is num) return value.toString().trim();
    return '';
  }

  /// The single group NAME of one service, or nothing. Never throws and never
  /// skips the service.
  List<String> _tagsOf(
    Map<Object?, Object?> service,
    Map<String, String> groups,
  ) {
    final id = _groupId(service['groupId']);
    if (id.isEmpty) return const [];
    final name = groups[id];
    return name == null ? const [] : <String>[name];
  }

  OtpAccount _parseService(
    Map<Object?, Object?> service,
    Map<Object?, Object?> otp,
    Map<String, String> groups,
  ) {
    final declared = _tokenType(otp['tokenType']);

    final serviceName = (_string(service['name']) ?? '').trim();
    final otpIssuer = (_string(otp['issuer']) ?? '').trim();
    _requireStringCap(serviceName, 'name');
    _requireStringCap(otpIssuer, 'issuer');
    _requireStringCap((_string(otp['account']) ?? '').trim(), 'account');
    final issuerRaw = otpIssuer.isNotEmpty ? otpIssuer : serviceName;
    final issuer = issuerRaw.isEmpty ? null : issuerRaw;
    // Plan D4: account → label → service name → placeholder.
    final accountName =
        _firstNonEmpty([otp['account'], otp['label'], service['name']]) ??
        _unnamedAccount;

    var secret = (_string(service['secret']) ?? '').trim();
    if (secret.isEmpty) {
      final fromLink = _secretFromLink(_string(otp['link'])) ?? '';
      if (_isRedactedPlaceholder(fromLink)) {
        // Source-specific: the file itself says the secret was withheld, so
        // "not valid Base32" would send the user looking for the wrong problem.
        throw const _Skip(
          SkipReason.invalidSecret,
          '2FAS hid this secret in the link; re-export with the secret',
        );
      }
      secret = fromLink;
    }
    if (secret.isEmpty) {
      throw const _Skip(SkipReason.invalidSecret, 'secret missing or empty');
    }
    _requireDecodableSecret(secret);

    // `tokenType` is the authority; there is no issuer heuristic (library doc).
    final type = declared;

    final int digits;
    final int period;
    final OtpAlgorithm algorithm;
    if (type == OtpType.steam) {
      digits = 5;
      algorithm = OtpAlgorithm.sha1;
      final rawPeriod = _integer(otp['period'], 'period');
      period = (rawPeriod != null && rawPeriod >= 1 && rawPeriod <= 600)
          ? rawPeriod
          : 30;
    } else {
      digits = _integer(otp['digits'], 'digits') ?? 6;
      period = _integer(otp['period'], 'period') ?? 30;
      algorithm = _algorithm(_string(otp['algorithm']));
    }

    final int counter;
    if (type == OtpType.hotp) {
      final parsed = _counter(otp);
      if (parsed == null) {
        throw const _Skip(
          SkipReason.invalidFields,
          'HOTP entry has no counter (tried "counter", "initialCounter")',
        );
      }
      counter = parsed;
    } else {
      counter = 0;
    }

    try {
      return OtpAccount(
        secret: secret,
        type: type,
        issuer: issuer,
        accountName: accountName,
        algorithm: algorithm,
        digits: digits,
        period: period,
        counter: counter,
        tags: _tagsOf(service, groups),
      );
    } on FormatException {
      // Out-of-contract numbers (digits 9, period 0, ...). The detail lists the
      // offending values only — never the secret.
      throw _Skip(
        SkipReason.invalidFields,
        'digits=$digits period=$period counter=$counter',
      );
    }
  }

  OtpType _tokenType(Object? raw) {
    final name = (_string(raw) ?? '').trim();
    // Absent/empty tokenType means TOTP (see class doc).
    if (name.isEmpty) return OtpType.totp;
    return switch (name.toUpperCase()) {
      'TOTP' => OtpType.totp,
      'HOTP' => OtpType.hotp,
      'STEAM' => OtpType.steam,
      _ => throw _Skip(
        SkipReason.unsupportedType,
        'tokenType=${_fragment(name)}',
      ),
    };
  }

  /// HOTP counter. `counter` is the official field; `initialCounter` is a
  /// defensive fallback for third-party writers, not observed in official
  /// exports.
  int? _counter(Map<Object?, Object?> otp) {
    for (final key in const ['counter', 'initialCounter']) {
      if (otp.containsKey(key)) {
        final value = _integer(otp[key], key);
        if (value != null) return value;
      }
    }
    return null;
  }

  /// Separates "an algorithm 2FAS allows but we cannot compute" from "an
  /// algorithm outside the 2FAS enum". [OtpAlgorithm.fromName] cannot make that
  /// distinction — it raises one [FormatException] for both — so the name is
  /// classified here, leaving `fromName` and its `otpauth://` callers untouched.
  OtpAlgorithm _algorithm(String? raw) {
    final name = (raw ?? '').trim();
    if (name.isEmpty) return OtpAlgorithm.sha1;
    final canonical = name.toUpperCase().replaceAll('-', '');
    try {
      return OtpAlgorithm.fromName(canonical);
    } on FormatException {
      if (_knownUnsupportedAlgorithms.contains(canonical)) {
        throw _Skip(SkipReason.unsupportedType, 'algorithm=$canonical');
      }
      throw _Skip(
        SkipReason.invalidFields,
        'unsupported algorithm ${_fragment(name)}',
      );
    }
  }

  /// True for a link secret the exporter deliberately withheld, e.g.
  /// `otpauth://totp/X?secret=[hidden]`. Defensive: the official Android
  /// exporter copies `link` verbatim, so this is not observed in its output.
  bool _isRedactedPlaceholder(String secret) =>
      secret.length >= 2 && secret.startsWith('[') && secret.endsWith(']');

  /// Extracts only the `secret` query parameter of an `otpauth://` link.
  /// Returns null for anything else, including malformed percent-encoding.
  String? _secretFromLink(String? link) {
    if (link == null || link.isEmpty) return null;
    final uri = Uri.tryParse(link.trim());
    if (uri == null || uri.scheme.toLowerCase() != 'otpauth') return null;
    try {
      final secret = uri.queryParameters['secret'];
      return (secret == null || secret.isEmpty) ? null : secret;
    } on FormatException {
      return null;
    }
  }

  /// Fails fast on a secret the OTP engine could not use, without letting
  /// `Base32.decode`'s message (which quotes the bad character) escape.
  void _requireDecodableSecret(String secret) {
    try {
      if (Base32.decode(secret).isEmpty) {
        throw const _Skip(
          SkipReason.invalidSecret,
          'secret decodes to zero bytes',
        );
      }
    } on FormatException {
      throw const _Skip(SkipReason.invalidSecret, 'secret is not valid Base32');
    }
  }
}

/// String-or-nothing accessor: a wrongly typed JSON value becomes `null`
/// instead of a `TypeError`, so label building can never throw.
String? _string(Object? value) => value is String ? value : null;

/// First value that is a non-blank String, trimmed; null when there is none.
String? _firstNonEmpty(List<Object?> candidates) {
  for (final candidate in candidates) {
    final value = (_string(candidate) ?? '').trim();
    if (value.isNotEmpty) return value;
  }
  return null;
}

/// Tolerant integer accessor. `null` when absent; [_Skip] when present but not
/// an integer. Integer-valued doubles and numeric strings are accepted;
/// fractional values are rejected rather than truncated.
int? _integer(Object? value, String field) {
  if (value == null) return null;
  if (value is int) return value;
  if (value is double && value == value.truncateToDouble()) {
    return value.toInt();
  }
  if (value is String) {
    final parsed = int.tryParse(value.trim());
    if (parsed != null) return parsed;
  }
  throw _Skip(SkipReason.invalidFields, '"$field" is not an integer');
}

/// Rejects a free-form string too long to belong in the vault. Byte length,
/// not code units: the ceiling has to mean the same thing for a Turkish issuer
/// as for an ASCII one.
void _requireStringCap(String value, String field) {
  if (utf8.encode(value).length > _maxStringBytes) {
    throw _Skip(
      SkipReason.invalidFields,
      '"$field" is over $_maxStringBytes bytes',
    );
  }
}

String? _label(String? issuer, String? name) {
  final i = _labelPart(issuer);
  final n = _labelPart(name);
  if (i.isNotEmpty && n.isNotEmpty) return '$i ($n)';
  if (i.isNotEmpty) return i;
  if (n.isNotEmpty) return n;
  return null;
}

/// Trimmed and clamped: a [SkippedEntry.label] is rendered verbatim, so an
/// oversized string from the file must not reach the preview.
String _labelPart(String? value) {
  final trimmed = (value ?? '').trim();
  return trimmed.length <= _maxLabelPart
      ? trimmed
      : '${trimmed.substring(0, _maxLabelPart)}…';
}

String _fragment(String value) => value.length <= _maxDetailFragment
    ? '"$value"'
    : '"${value.substring(0, _maxDetailFragment)}…"';

/// Internal control-flow signal: "drop this entry, keep the file".
class _Skip implements Exception {
  final SkipReason reason;
  final String detail;
  const _Skip(this.reason, this.detail);
}
